const dictionary = {
    "kuum": "жаркий",
    "mahtuma": "вмещать",
    "lahke": "добрый",
    "hädaldama": "жаловаться",
    "tõsine": "серьезный",
    "arutama": "обсуждать",
    "astuma": "заходить",
    "kujutama": "представлять",
    "keerama": "вращать",
    "virisema":"ныть",
    "aknalaud":"подоконник",
    "nuusutama":"нюхать",
    "peaaegu":"почти",
    "pooleli":"наполовину",
    "segi":"беспорядок",
    "hüüdma":"кричать, звать",
    "muru":"трава, газон",
    "lehvitama":"махать",
    "kõndima":"гулять",
    "krabistama":"шуршать",
    "aina":"только, лишь, так и",
    "sussid":"тапки",
    "pink":"скамья",
    "latern":"светильник, фонарь",
    "tangud":"крупа",
    "sült":"холодец",
    "süda paha":"тошнит",
    "linnu toidumaja":"кормушка",
    "kuum":"palav",
    "hoopis":"вместо",
    "pidama":"tähistama",
    "pea on täitsa segi":"каша в голове",
    "kirjand":"сочинение",
    "hoidma":"держать",
    "taat ja memm":"дед и баба",
    "söödav":"съедобный",
    "äkki":"может быть",
    "viide":"намек",
    "isegi":"",
    "lööma":"взбить, бить",
    "hapuma":"киснуть",
    "nukke":"грустный",
    "lõik":"кусок",
    "kokku saama":"собраться",
    "oma silm on kuningas":"лучше сто раз увидеть",
    "õiendama":"вытягивать, выпрямлять",
    "vastik":"противный",
    "päev okinni":"день занят",
    "igaks juhuks":"на всякий случай",
    "kabe":"шашки",
    "paistma":"виднеться, торчать",
    "käed kinni":"руки заняты",
    "eraldi":"раздельно",
    "ära sulama":"таять",
    "paik":"место, местность",
    "nautima":"наслаждаться",
    "õhkkond":"атмосфера",
    "omadus":"свойство",
    "suuline":"устный",
    "mõned":"некоторые, кое-какие",
    "pistma":"сунуть",
    "peitma":"спрятать",
    "sattuma":"попасть",
    "valama":"налить, насыпать",
    "lagi":"потолок",
    "kukkuma":"упасть",
    "siirduma":"направляться",
    "maha":"на землю, вниз",
    "hellitama":"баловать",
    "kahtlema":"сомневаться",
    "grippi jääma":"заболеть",
    "voolama":"течь",
    "oja":"ручей",
    "kann":"кувшин",
    "jõuama":"прибывать, смочь",
    "ülejäänud":"лишний",
    "lapik":"приплюснутый",
    "sisustus":"оснащение",
    "tekkima":"появиться, образоваться",
    "valge":"белый, светлый",
    "pikutama":"лежать",
    "süütma":"разжигать",
    "viib keele alla":"язык проглотишь",
    "ümbrik":"конверт",
    "kaunistama":"украшать",
    "range":"строгий, требовательный",
    "soolaleivapidu":"новоселье",
    "segama":"запутать",
    "lina":"простынь",
    "kraanikauss":"раковина",
    "mõnus":"приятный",
    "miski":"что-то, ничто",
    "praema":"жарить",
    "keetma":"варить",
    "koerailm":"собачья погода",
    "õudne":"страшный",
    "laisk":"ленивый",
    "tihe":"густой, плотный",
    "eks ole":"не так ли, ведь",
    "ajama":"гнать, вгонять",
    "lobisema":"болтать",
    "juttu ajama":"разговаривать",
    "põõsas":"куст",
    "kiitma":"хвалить",
    "vahel":"между",
    "kitsas, lai":"узкий, тесный",
    "tasakaal":"равновесие",
    "maitse asi":"дело вкуса",
    "lahke":"добрый",
    "lahendus":"решение",
    "mõlemad":"оба",
    "täiesti":"полностью",
    "seletama":"объяснять",
    "karjuma":"кричать",
    "kuulus":"известный",
    "hilja":"поздно",
    "juhuslikult":"случайно",
    "otsekohe":"сразу",
    "valmistama":"готовить",
    "üles leidma":"находить",
    "saadik":"начиная",
    "vist":"наверное",
    "keerama":"вращать",
    "päris":"совсем, довольно",
    "eriti":"особенно",
    "elamus":"чувство",
    "pole õrna aimugi":"понятия не имею",
    "veidi":"немного",
    "lõhkuma":"разбить, сломать",
    "kahvel":"вилка",
    "kauss":"миска",
    "loeng":"лекция",
    "tegevus":"занятие",
    "tass":"чашка",
    "ikka":"все, всегда",
    "keskkond":"окружающая среда",
    "näerma":"встретиться",
    "paat":"лодка",
    "suunama":"направить",
    "laekama":"поступить",
    "saabuma":"прибыть",
    "vald":"волость",
    "pakiline":"срочный",
    "tingimata":"непременно",
    "paiku":"около",
    "viisakas":"вежливый",
    "edukas":"успешный",
    "hõivatud":"занятой",
    "ehk":"või",
    "kindlasti":"несомненно",
    "kuid":"однако, но все же",
    "kunagi":"когда-то, когда-нибудь",
    "mõnikord":"иногда",
    "olgu":"ладно",
    "õnneks":"к счастью",
    "üldiselt":"в общем",
    "tark":"разумный",
    "vari":"тень",
    "sugulane":"родственник",
    "elukaaslane":"спутник жизни",
    "äi":"отец супруга",
    "ämm":"мать супруга",
    "onupoeg":"кузен",
    "tekk":"одеяло",
    "veekeetja, kann":"чайник",
    "kuulutus":"объявление",
    "eriala":"специальность выученная",
    "elukutse":"профессия (кем работаю)",
    "teekann":"заварник",
    "kiir":"луч",
    "oks":"ветка",
    "pesa":"гнездо",
    "imelik":"странный",
    "tore":"милый",
    "ümar":"круглый",
    "ruudeline":"в клетку",
    "täpiline":"в крапинку",
    "juurvili":"корнеплод",
    "nimekiri":"список",
    "köögivili":"овощи",
    "uba":"фасоль",
    "riie":"ткань",
    "silt":"вывеска, табличка",
    "inetu":"некрасивый",
    "kasulik":"полезный",
    "kurjuma":"ругаться",
    "närima":"грызть",
    "kõva":"твердый",
    "seltskond":"компания",
    "tikker":"крыжовник",
    "aine":"предмет, ингредиент",
    "kaer":"овес",
    "kiirustav":"спешащий",
    "külaline":"гость",
    "taim":"зелень, растения",
    "toit":"еда",
    "üllatus":"сюрприз",
    "jutt":"рассказ",
    "nälg":"голод",
    "katus":"крыша",
    "kelder":"подвал",
    "korsten":"труба",
    "lagi":"потолок",
    "vaikne":"тихий",
    "igav":"скучный",
    "korralik":"приличный, аккуратный",
    "oluline":"важный",
    "üürnik":"арендатор",
    "male":"шахматы",
    "nõu":"совет, посуда",
    "tagasihoidlik":"скромный",
    "trepikoda":"подъезд",
    "kiik":"качель",
    "padi":"подушка",
    "sahtel":"ящик",
    "triikraud":"утюг",
    "vaip":"ковер",
    "ahi":"печь",
    "kära":"шум",
    "nagi":"вешалка стоящая",
    "töökoda":"мастерская",
    "avaja":"открывашка",
    "juhe":"провод",
    "tikk":"спичка",
    "alumine":"нижний",
    "kaunis":"прекрасный",
    "pererahvas":"хозяева",
    "armas":"милый",
    "kaal":"весы",
    "kutse":"приглашение",
    "tuju":"настроение",
    "vahva":"классный",
    "juur":"корень",
    "kuum":"горячий",
    "muld":"почва",
    "vaht":"пена",
    "just":"именно, только что",
    "lubama":"обещать, разрешать",
    "ammu":"давно",
    "piisav":"достаточный",
    "pidev":"постоянный",
    "harva":"редко",
    "vaid":"лишь",
    "kohalik":"местный",
    "rahus":"спокойно",
    "aus":"честный",
    "põnev":"увлекательный",
    "liha":"мышечная ткань",
    "tegelikult":"на самом деле",
    "Sellisel juhul":"в таком случае",
    "häbelik":"скромный",
    "õel, vihane":"злой",
    "mainima":"упоминать, назвать",
    "lõbutse hästi":"хорошо повеселись",
    "esindama":"представлять",
    "kinni pidama":"останавливать",
    "täiuslik":"идеально",
    "relv":"оружие",
    "võimas":"мощный",
    "soovitus":"пожелание",
    "paluma":"просить",
    "soovitama":"рекомендовать",
    "toidukord":"прием пищи",
    "otsus":"решение",
    "ettevalmistus":"приготовление",
    "niipea kui võimalik":"как можно скорее",
    "mulle näib":"мне кажется",
    "tunne":"чувство",
    "tingimus":"условие",
    "saavutama":"достигать"

}

