const dictionary = [
	["aina - mis te aina toas istute - что вы в комнате так и сидите"],
//	["ajutiselt - временно"],
	["algselt - mis see sõna algselt tähendas? - что это слово первоначально означало?"],
//	["algul - в начале"],
//	["alles - только что, едва"],
	["allpool - kaks korrust allpool - двумя этажами ниже"],
	["arvatavasti - teda see arvatavasti ei huvita - его это, вероятно, не интересует"],
	["ammu - ma ei ole teda ammu näinud - я его давно не видел"],
//	["avalikult - публично"],
//	["edaspidi - впредь"],
//	["eelkõige - прежде всего"],
//	["eelnevalt - заранее"],
	["eemal - eemal asuma - находиться в отдалении, поодаль"],
//	["eeskätt - прежде всего"],
//	["eespool - впереди"],
//	["ega - и не"],
	["ehk - ehk tahad süüa? - может быть, хочешь есть?"],
	["ehk - aeroplaan ehk lennuk - аэроплан, или самолёт"],
//	["eks - разумеется, конечно"],
	["eks - eks ma öelnud - ведь я же говорил"],
	["eks - eks ole ilus? - не правда ли, красиво?"],
	["enamasti - ta töötab enamasti kodus - он работает большей частью дома"],
//	["endiselt - по-прежнему"],
	["eraldi - nad käisid siin koos ja eraldi - они приходили сюда вместе и порознь"],
	["eriti - eriti viimasel ajal - особенно в последнее время"],
//	["esialgu - сначала"],
//	["esile - на передний план"],
	["esiteks - ta punastas rohkem kui esiteks - она покраснела больше, чем вначале"],
	["esmakordselt - näen seda esmakordselt - впервые вижу это"],
//	["esmalt - прежде всего"],
//	["ettepoole - вперед"],
//	["harilikult - обычно"],
	["harva - seda juhtub harva - это случается редко"],
	["hilja - on juba päris hilja - уже довольно ПОЗДНО"],
	["hiljuti - majad olid hiljuti värvitud - дома были покрашены недавно"],
	["hirmsasti - tahan hirmsasti magada - мне жутко хочется спать "],
	["hoopis - kõik see juhtus hoopis hiljem - всё это случилось ГОРАЗДО позже"],
	["hoopis - ta on hoopis haige - наоборот, он болен"],
//	["igati - во всех отношениях"],
//	["iialgi - никогда, отродясь"],
	["ikka - tal oli õigus nagu ikka - он был прав, как ВСЕГДА"],
	["ikka - ta on ikka veel siin - он ВСЁ ЕЩЁ здесь"],
	["ikka - lähed jalgsi? jalgsi ikka - пешком пойдёшь? КОНЕЧНО, пешком"],
//	["ikkagi - все же"],
	["ilmselt - mees oli ilmselt väsinud - мужчина был явно уставший"],
	["ilmselt - sa ilmselt ei tunne teda - ты, очевидно, его и не знаешь "]
//	["iseenesest - само собой"],
	["isegi - isegi tema ei tea - даже он не знает"],
	["isegi - tal on tööd isegi palju - у него И БЕЗ ТОГО работы много"],
	["iganes - aitas mind, kuidas iganes sai - он помогал мне как только мог"],
	["iganes - võta, mis sa iganes soovid! - бери всё, что только желаешь"],
	["isiklikult - teatage talle isiklikult - сообщите ему лично"],
//	["jala - пешком"],
	["jalgsi - jalgsi matkamine on tervislik - пеший поход полезен здоровью"],
	["ju - sa ju aitad mind - ты же мне поможешь"],
	["juhuslikult - ostsin raamatu juhuslikult - я купил книгу случайно"],
//	["julgelt - смело"],
//	["justkui - как бы"],
	["just - jõudsin just koju - я только что вернулся домой"],
	["just - ootasime just sind - мы ждали именно тебя"],
	["jälle - kevad on jälle käes - снова настала весна"],
	["järel - suve järel tuleb sügis - следом за летом идёт осень"],
	["järel - läksin ees, koer järel - я шёл впереди, собака следом"],
	["järelikult - sajab vihma, järelikult randa me ei lähe - идёт дождь, следовательно, на пляж мы не пойдём"],
	["järgi - seaduse järgi toimima - действовать по/согласно закону"],
//	["järsku - вдруг"],
//	["jätkuvalt - по-прежнему"],
//	["kallale - к, на"],
	["kaugel - kaugel paistis järv - вдали/вдалеке виднелось озеро"],
	["kehvasti - tunnen end kehvasti - я себя неважно чувствую"],
	["keskel - veetsin pühapäeva pere keskel - я провёл воскресенье среди/в кругу семьи"],
//	["kihlatud - помолвлен"],
	["kindlasti - ta tuleb kindlasti - он обязательно придёт"],
	["kindlasti - ta on meist kindlasti kõige vanem - он, несомненно, старше всех нас"],
//	["kodunt - из дому"],
//	["kogemata - случайно"],
//	["koguni - даже"],
	["kohal - järve kohal mäe otsas oli loss - над озером на горе стоял замок"],
	["kohal - auto peatus aiavärava kohal - автомобиль остановился на месте калитки"],
//	["kohati - иногда, в некоторых местах"],
	["kohe - kohe pärast kooli lõpetamist - сразу после окончания школы"],
	["kohe - jõgi on kohe maja taga - река сразу за домом"],
	["kohe - tule kohe siia! - иди сейчас же сюда!"],
//	["kord - однажды, раз"],
	["korduvalt - seda on korduvalt juhtunud - такое случалось многократно"],
	["korraga - ärge rääkige korraga! - не говорите одновременно/разом!"],
//	["korraks - на мгновение"],
//	["kuivõrd - поскольку"],
	["kunagi - ta ei tee seda kunagi - он этого никогда не сделает"],
	["kunagi - kunagi töötasime koos - когда-то мы работали вместе"],
	["kuskil - kuskil lähedal - где-то поблизости"],
	["kõigepealt - turistid sõitsid kõigepealt hotelli - прежде всего туристы поехали в гостиницу"],
	["kõikjal - käivad kõikjal koos - они везде ходят вместе"],
	["kõrgel - päike on juba üsna kõrgel - солнце уже довольно ВЫСОКО"],
	["kõrval - istusin autojuhi kõrval - я сидел рядом с шофёром"],
	["kõrvuni - ta on tüdrukusse kõrvuni armunud - он по уши влюблён в девушку "],
//	["kõrvuti - бок о бок"],
//	["kõvasti - твердо, крепко, плотно, наглухо"],
	["külge - toodetele kleebiti sildid külge - к изделиям приклеили ярлыки"],
	["küll - siin küll kilogrammi ei ole - здесь килограмма ТОЧНО нет"],
	["küll - küll on tore, et sa tulid! - ой, как хорошо, что ты пришёл!"],
	["küll -  siin on ruumi küll - здесь места достаточно"],
//	["küllaltki - вполне, достаточно"],
//	["lahku - врозь"],
//	["lahus - отдельно"],
//	["lahutatud - отделенный"],
//	["laiali - в разные стороны"],
	["las - пусть"],
//	["lausa - прямо, совсем"],
//	["ligi - близко"],
//	["loodetavasti - надеюсь, что"],
	["loomulikult - естественно, понятное дело"],
//	["lukku - в закрытом положении"],
	["lõplikult - окончательно"],
	["lõpuks - в конце концов"],
	["läbi - через, сквозь"],
	["lähedal - близко"],
	["lähemal - ближе"],
	["lühidalt - кратко"],
//	["maas - на земле, внизу"],
	["maha - вниз, на землю"],
//	["majanduslikult - экономически"],
	["meeleldi - с удовольствием, охотно"],
	["meelsasti - охотно"],
//	["millegipärast - почему-то"],
//	["muidu - в противном случае"],
	["muide - кстати, между прочим"],
//	["mujal - в другом месте"],
//	["muuseas - кстати"],
	["mõnikord - иногда"],
//	["märgatavalt - заметно"],
	["mööda - вдоль, мимо"],
	["niimoodi - таким образом"],
	["niipea - как только"],
	["niisama - такой же"],
//	["niisiis - таким образом"],
//	["niiviisi - так"],
	["nimelt - а именно"],
//	["nõnda - вот так, так, таким образом"],
	["nõus - согласен"],
	["näiteks - например"],
	["nähtavasti - очевидно"],
//	["ometi - тем не менее, все же"],
	["ootamatult - внезапно"],
	["otsa - конец, до конца, торцевой+"],
	["otse - прямо"],
	["otsekohe - сразу, немедленно"],
//	["paraku - к сожалению"],
//	["paratamatult - неизбежно"],
	["peaaegu - почти"],
//	["peagi - скоро"],
	["peal - наверху, над"],
	["peamiselt - в основном, преимущественно"],
//	["pilves - облачно"],
//	["pisut - немного"],
	["pooleli - незаконченный, наполовину"],
//	["poolt - на полпути"],
//	["purjus - пьяный"],
	["puudu - отсутствует"],
	["pärastlõunal - после полудня"],
	["päris - вполне, довольно"],
	["päriselt - на самом деле, окочательно"],
	["püsti - стоя"],
	["rahul - удовлетворен"],
	["rahus - спокойно"],
//	["rikki - сломан"],
	["risti - поперек"],
	["sageli - часто"],
//	["salaja - тайно"],
//	["samas - в то же время"],
	["samuti - также"],
	["seejärel - затем"],
	["sees - внутри"],
	["segi, segamini- вперемешку"],
	["sellepärast - поэтому"],
	["seni - до сих пор"],
	["siiasamasse - сюда, тут же"],
	["siiski - тем не менее, всё-таки, ka siis, и тогда"],
	["sisuliselt - по сути"],
	["suhteliselt - относительно, сравнительно, довольно"],
//	["sõltuvalt - в зависимости"],
//	["sügavalt - глубоко"],
//	["süüdi - виноват"],
//	["taas - снова, jälle"],
//	["tarvis - нужно"],
//	["tasa - тихо, медленно"],
	["tavaliselt - обычно"],
//	["teadlikult - сознательно"],
	["tegelikult - фактически, на самом деле"],
	["teisiti - иначе, по-другому"],
	["tihti - часто"],
//	["tingimata - непременно"],
//	["tohutu - огромный"],
//	["tookord - тогда"],
	["tõesti - действительно, правда"],
	["tõsiselt - серьезно"],
	["täiesti - полностью"],
	["täis - полный"],
	["umbes - примерно"],
	["vaatamata - несмотря на"],
//	["vabatahtlikult - добровольно"],
//	["vaevalt - едва ли"],
	["vahel - иногда"],
	["vaid - только, лишь"],
//	["vait - молчи"],
	["valmis - готов"],
	["vara - рано"],
	["varem - раньше"],
	["varsti - скоро"],
	["vastas - напротив, напротив"],
	["vastu - против"],
	["vastupidi - наоборот"],
	["veidi - немного"],
	["viimati - в последний раз"],
	["vist - вероятно, наверное"],
//	["võrdselt - равномерно"],
	["väljas - снаружи"],
//	["õieti - правильно"],
	["õnneks - к счастью"],
	["äkki - вдруг, может быть"],
//	["äärmiselt - чрезвычайно"],
	["üksi - один"],
//	["üksinda - один"],
	["ükski - ни один"],
	["ülal - вверху"],
	["üldiselt - в общем"],
	["üldse - вообще, в общем"],
	["üsna - довольно, весьма"],
]