const dictionary = [
	["aina - mis te aina toas istute - что вы в комнате так и сидите"],
//	["ajutiselt - временно"],
	["algselt - mis see sõna algselt tähendas? - что это слово первоначально означало?"],
//	["algul - в начале"],
//	["alles - только что, едва"],
	["allpool - kaks korrust allpool - двумя этажами ниже"],
	["arvatavasti - teda see arvatavasti ei huvita - его это, вероятно, не интересует"],
	["ammu - ma ei ole teda ammu näinud - я его давно не видел"],
//	["avalikult - публично"],
//	["edaspidi - впредь"],
//	["eelkõige - прежде всего"],
//	["eelnevalt - заранее"],
	["eemal - eemal asuma - находиться в отдалении, поодаль"],
//	["eeskätt - прежде всего"],
//	["eespool - впереди"],
//	["ega - и не"],
	["ehk - ehk tahad süüa? - может быть, хочешь есть?"],
	["ehk - aeroplaan ehk lennuk - аэроплан, или самолёт"],
//	["eks - разумеется, конечно"],
	["eks - eks ma öelnud - ведь я же говорил"],
	["eks - eks ole ilus? - не правда ли, красиво?"],
	["enamasti - ta töötab enamasti kodus - он работает большей частью дома"],
//	["endiselt - по-прежнему"],
	["eraldi - nad käisid siin koos ja eraldi - они приходили сюда вместе и порознь"],
	["eriti - eriti viimasel ajal - особенно в последнее время"],
//	["esialgu - сначала"],
//	["esile - на передний план"],
	["esiteks - ta punastas rohkem kui esiteks - она покраснела больше, чем вначале"],
	["esmakordselt - näen seda esmakordselt - впервые вижу это"],
//	["esmalt - прежде всего"],
//	["ettepoole - вперед"],
//	["harilikult - обычно"],
	["harva - seda juhtub harva - это случается редко"],
	["hilja - on juba päris hilja - уже довольно ПОЗДНО"],
	["hiljuti - majad olid hiljuti värvitud - дома были покрашены недавно"],
	["hirmsasti - tahan hirmsasti magada - мне жутко хочется спать "],
	["hoopis - kõik see juhtus hoopis hiljem - всё это случилось ГОРАЗДО позже"],
	["hoopis - ta on hoopis haige - наоборот, он болен"],
//	["igati - во всех отношениях"],
//	["iialgi - никогда, отродясь"],
	["ikka - tal oli õigus nagu ikka - он был прав, как ВСЕГДА"],
	["ikka - ta on ikka veel siin - он ВСЁ ЕЩЁ здесь"],
	["ikka - lähed jalgsi? jalgsi ikka - пешком пойдёшь? КОНЕЧНО, пешком"],
//	["ikkagi - все же"],
	["ilmselt - mees oli ilmselt väsinud - мужчина был явно уставший"],
	["ilmselt - sa ilmselt ei tunne teda - ты, очевидно, его и не знаешь "]
//	["iseenesest - само собой"],
	["isegi - isegi tema ei tea - даже он не знает"],
	["isegi - tal on tööd isegi palju - у него И БЕЗ ТОГО работы много"],
	["iganes - aitas mind, kuidas iganes sai - он помогал мне как только мог"],
	["iganes - võta, mis sa iganes soovid! - бери всё, что только желаешь"],
	["isiklikult - teatage talle isiklikult - сообщите ему лично"],
//	["jala - пешком"],
	["jalgsi - jalgsi matkamine on tervislik - пеший поход полезен здоровью"],
	["ju - sa ju aitad mind - ты же мне поможешь"],
	["juhuslikult - ostsin raamatu juhuslikult - я купил книгу случайно"],
//	["julgelt - смело"],
//	["justkui - как бы"],
	["just - jõudsin just koju - я только что вернулся домой"],
	["just - ootasime just sind - мы ждали именно тебя"],
	["jälle - kevad on jälle käes - снова настала весна"],
	["järel - suve järel tuleb sügis - следом за летом идёт осень"],
	["järel - läksin ees, koer järel - я шёл впереди, собака следом"],
	["järelikult - sajab vihma, järelikult randa me ei lähe - идёт дождь, следовательно, на пляж мы не пойдём"],
	["järgi - seaduse järgi toimima - действовать по/согласно закону"],
//	["järsku - вдруг"],
//	["jätkuvalt - по-прежнему"],
//	["kallale - к, на"],
	["kaugel - kaugel paistis järv - вдали/вдалеке виднелось озеро"],
	["kehvasti - tunnen end kehvasti - я себя неважно чувствую"],
	["keskel - veetsin pühapäeva pere keskel - я провёл воскресенье среди/в кругу семьи"],
//	["kihlatud - помолвлен"],
	["kindlasti - ta tuleb kindlasti - он обязательно придёт"],
	["kindlasti - ta on meist kindlasti kõige vanem - он, несомненно, старше всех нас"],
//	["kodunt - из дому"],
//	["kogemata - случайно"],
//	["koguni - даже"],
	["kohal - järve kohal mäe otsas oli loss - над озером на горе стоял замок"],
	["kohal - auto peatus aiavärava kohal - автомобиль остановился на месте калитки"],
//	["kohati - иногда, в некоторых местах"],
	["kohe - kohe pärast kooli lõpetamist - сразу после окончания школы"],
	["kohe - jõgi on kohe maja taga - река сразу за домом"],
	["kohe - tule kohe siia! - иди сейчас же сюда!"],
//	["kord - однажды, раз"],
	["korduvalt - seda on korduvalt juhtunud - такое случалось многократно"],
	["korraga - ärge rääkige korraga! - не говорите одновременно/разом!"],
//	["korraks - на мгновение"],
//	["kuivõrd - поскольку"],
	["kunagi - ta ei tee seda kunagi - он этого никогда не сделает"],
	["kunagi - kunagi töötasime koos - когда-то мы работали вместе"],
	["kuskil - kuskil lähedal - где-то поблизости"],
	["kõigepealt - turistid sõitsid kõigepealt hotelli - прежде всего туристы поехали в гостиницу"],
	["kõikjal - käivad kõikjal koos - они везде ходят вместе"],
	["kõrgel - päike on juba üsna kõrgel - солнце уже довольно ВЫСОКО"],
	["kõrval - istusin autojuhi kõrval - я сидел рядом с шофёром"],
	["kõrvuni - ta on tüdrukusse kõrvuni armunud - он по уши влюблён в девушку "],
//	["kõrvuti - бок о бок"],
//	["kõvasti - твердо, крепко, плотно, наглухо"],
	["külge - toodetele kleebiti sildid külge - к изделиям приклеили ярлыки"],
	["küll - siin küll kilogrammi ei ole - здесь килограмма ТОЧНО нет"],
	["küll - küll on tore, et sa tulid! - ой, как хорошо, что ты пришёл!"],
	["küll - siin on ruumi küll - здесь места достаточно"],
//	["küllaltki - вполне, достаточно"],
//	["lahku - врозь"],
//	["lahus - отдельно"],
//	["lahutatud - отделенный"],
//	["laiali - в разные стороны"],
	["las - las ma mõtlen natuke - дай я немного подумаю"],
	["las - las ta räägib mis tahab - пускай говорит что хочет"],
//	["lausa - прямо, совсем"],
//	["ligi - близко"],
//	["loodetavasti - надеюсь, что"],
	["loomulikult - loomulikult oli see risk - естественно, это был риск"],
	["loomulikult - tüdrukul on loomulikult blondid sirged juuksed - у девочки от природы светлые прямые волосы"],
//	["lukku - в закрытом положении"],
//	["lõplikult - окончательно"],
	["lõpuks - tulid, lõpuks ometi! - наконец-то ты пришёл!"],
	["lõpuks -  kes ta siis lõpuks on? - кто же он в конце концов?"],
	["läbi - räägib läbi nina - он говорит через нос "],
	["läbi -  sõitsime Tartust läbi - мы проехали через Тарту"],
	["lähedal - kevad on juba lähedal - весна уже недалеко"],
	["lähemal - mida lähemal, seda parem - чем ближе, тем лучше"],
	["lühidalt - räägi lühidalt - расскажи вкратце"],
//	["maas - на земле, внизу"],
	["maha - pani lapse maha - опустил ребёнка на землю"],
	["maha - võta mantel maha - сними пальто"],
//	["majanduslikult - экономически"],
	["meeleldi - meeleldi tuleksin teiega kaasa - с удовольствием пошёл бы с вами"],
//	["meelsasti - охотно"],
//	["millegipärast - почему-то"],
//	["muidu - в противном случае"],
	["muide - muide, ma ei tööta enam seal - кстати, я уже там не работаю"],
//	["mujal - в другом месте"],
//	["muuseas - кстати"],
	["mõnikord - mõnikord on raske - иногда бывает нелегко"],
//	["märgatavalt - заметно"],
	["mööda - jalutab linna mööda - гуляет по городу"],
	["mööda - auto sõitis mööda - машина проехала мимо"],
	["niimoodi - niimoodi ei tohi rääkida - так нельзя говорить"],
	["niipea - alustan niipea kui olen valmis - начну как только буду готов"],
	["niisama - seda asja ma niisama ei jäta! - я это дело просто так не оставлю!"],
	["niisama - lõpetasin kooli niisama hästi kui mu sõbranna - закончил школу так же хорошо как моя подруга"],
//	["niisiis - таким образом"],
//	["niiviisi - так"],
	["nimelt - kavatseb autot osta, aga ma ei tea, missugust nimelt - планирует купить машину, но не знаю какую ИМЕННО"],
//	["nõnda - вот так, так, таким образом"],
	["nõus - sellega mina pole nõus - с этим я не согласен"],
	["näiteks - puuviljad, näiteks banaan ja õun - фрукты, например, банан и яблоко"],
	["nähtavasti - nähtavasti see ei meeldinud talle - видимо, это не понравилось ему"],
//	["ometi - тем не менее, все же"],
	["ootamatult - ootamatult kõlas uksekell - неожиданно раздался звонок в дверь"],
	["otsa - pane pilt naela otsa - повесь картину на гвоздь!"],
	["otse - kas lähme otse või paremale? - пойдём прямо или направо?"],
	["otsekohe - tulge otsekohe - приходите немедленно/сразу же"],
//	["paraku - к сожалению"],
//	["paratamatult - неизбежно"],
	["peaaegu - peaaegu kõik olid kohal - почти все были на месте"],
//	["peagi - скоро"],
	["peal - leib on laua peal - хлеб на столе"],
	["peamiselt - ma töötan peamiselt kodus - в основном я работаю дома"],
//	["pilves - облачно"],
//	["pisut - немного"],
	["pooleli - kõik tööd on pooleli - все работы не докончены / остались наполовине"],
//	["poolt - на полпути"],
//	["purjus - пьяный"],
	["puudu - kaks minutit on kahest puudu - без двух минут два"],
	["puudu - kaks hammast on puudu - не хватает двух зубов"],
	["pärastlõunal - reede pärastlõunal sõidan maale - в пятницу после полудня еду в деревню"],
	["päris - väljas on juba päris pime - на улице уже СОВСЕМ стемнело"],
	["päris - oleme juba päris lähedal - мы уже ДОВОЛЬНО близко"],
	["püsti - aita mind püsti - помоги мне встать (стоя)"],
	["rahul - ta on oma eluga väga rahul - он очень доволен своей жизнью"],
//	["rikki - сломан"],
	["risti - läks risti üle platsi - перешел площадь поперек"],
//	["salaja - тайно"],
//	["samas - в то же время"],
	["samuti - elab samuti kui teised - живёт так же, как и другие"],
	["seejärel - затем"],
	["sees - seina sees oli auk - в стене (внутри) была дыра"],
	["segi, segamini- вперемешку"],
	["sellepärast - tahtsin sind näha, sellepärast ma tulin - хотел тебя увидеть, поэтому и пришёл"],
	["seni - selles majas olime seni elanud - в этом доме мы до сих пор жили"],
	["siiasamasse - сюда, тут же"],
	["siiski - ta siiski tuli - он всё-таки пришёл"],
	["sisuliselt - по сути"],
	["suhteliselt - märts oli suhteliselt soe - март был относительно тёплым"],
//	["sõltuvalt - в зависимости"],
//	["sügavalt - глубоко"],
//	["süüdi - виноват"],
//	["taas - снова, jälle"],
//	["tarvis - нужно"],
//	["tasa - тихо, медленно"],
	["tavaliselt - hilines nagu tavaliselt - он опоздал, как обычно"],
//	["teadlikult - сознательно"],
	["tegelikult - ta on tegelikult pikem, kui välja paistab - на самом деле он выше, чем выглядит"],
	["tegelikult - teoreetiliselt on nii, aga tegelikult? - теоретически это так, а в жизни?"],
	["teisiti - mõned mõtlevad teisiti - некоторые думают иначе / по другому"],
//	["tingimata - непременно"],
//	["tohutu - огромный"],
//	["tookord - тогда"],
	["tõesti - ma tõesti ei tea, kes seda tegi - я, правда, не знаю, кто это сделал"],
	["tõsiselt - räägid sa tõsiselt või teed nalja? - ты говоришь серьёзно или шутишь?"],
	["tõsiselt - valmistun tõsiselt eksamiteks - я серьёзно готовлюсь к экзаменам"],
	["täiesti - olen täiesti üksi - я совсем один (полностью)"],
	["täis - täis klaas - полный стакан"],
	["täis - väljas on täis kevad - весна в полном разгаре"],
	["umbes - ta on umbes minupikkune - он ростом примерно с меня"],
	["vaatamata - kõigele vaatamata - несмотря ни на что"],
//	["vabatahtlikult - добровольно"],
//	["vaevalt - едва ли"],
	["vahel - kella kümne ja üheteistkümne vahel - между десятью и одиннадцатью часами"],
	["vahel - käisime vahel teatris - иногда мы ходили в театр"],
	["vaid - tähtis pole mitte vorm, vaid sisu - важна не форма, лишь содержание"],
	["vaid - elasin seal vaid lühikest aega - я прожил там ЛИШЬ короткое время"],
//	["vait - молчи"],
	["valmis - töö on valmis - работа готова "],
	["vara - vara hommikul - рано утром"],
	["varem - kolm päeva varem - [на] три дня раньше"],
	["varsti - varsti on suvi - скоро [будет] лето"],
	["vastas - kamina vastas on diivan - напротив камина стоит диван"],
	["vastu - kool ehitati lasteaia vastu - школу построили напротив детского сада"],
	["vastupidi - enne rääkisid nii ja nüüd vastupidi - раньше ты говорил одно, а теперь ПРОТИВОПОЛОЖНОЕ/НАОБОРОТ"],
	["veidi - lisa veidi soola - добавь немножко соли "],
	["viimati - millal sa teda viimati nägid? - когда ты видел его в последний раз?"],
	["vist - вероятно, наверное"],
//	["võrdselt - равномерно"],
	["väljas - väljas puhub tuul - снаружи дует ветер"],
//	["õieti - правильно"],
	["õnneks - к счастью"],
	["äkki - tuul tõusis äkki - ветер поднялся вдруг"],
	["äkki - äkki on ta haigeks jäänud? - вдруг ~ а что если он заболел? "],
//	["äärmiselt - чрезвычайно"],
	["üksi - ta elab üksi - он живёт один "],
//	["üksinda - один"],
	["ükski - siin ei aita ükski rohi - здесь никакое лекарство не поможет"],
	["ülal - вверху"],
	["üldiselt - üldiselt oleme rahul - в общем[-то] мы довольны"],
	["üldse - mis siin üldse toimub? - что тут вообще происходит?"],
	["üsna - kõneleb üsna head eesti keelt - он достаточно хорошо говорит по-эстонски"],
]