const dictionary = {
    "mahtuma": "вмещать",
    "hädaldama": "жаловаться",
    "arutama": "обсуждать",
    "astuma": "заходить",
    "kujutama": "представлять",
    "keerama": "вращать",
    "virisema":"ныть",
    "nuusutama":"нюхать",
    "hüüdma":"кричать, звать",
    "kõndima":"гулять",
    "lehvitama":"махать",
    "krabistama":"шуршать",
    "süda paha":"тошнит",
    "pidama":"tähistama",
    "hoidma":"держать",
    "lööma":"взбить, бить",
    "hapuma":"киснуть",
	"kokku saama":"собраться",
    "oma silm on kuningas":"лучше сто раз увидеть",
    "päev okinni":"день занят",
    "õiendama":"вытягивать, выпрямлять",
    "paistma":"виднеться, торчать",
    "käed kinni":"руки заняты",
    "ära sulama":"таять",
    "nautima":"наслаждаться",
    "pistma":"сунуть",
    "peitma":"спрятать",
    "sattuma":"попасть",
    "valama":"налить, насыпать",
    "lubama":"обещать, разрешать",
    "esindama":"представлять",
    "kinni pidama":"останавливать",
    "paluma":"просить",
    "soovitama":"рекомендовать",
    "mulle näib":"мне кажется",
    "saavutama":"достигать",
	"tasuma":"maksma",
	"pöörama":"keerama",
	"maha jääma":"отстать",
	"maha minema":"сойти выйти",
    "kukkuma":"упасть",
    "siirduma":"направляться",
    "hellitama":"баловать",
    "kahtlema":"сомневаться",
    "grippi jääma":"заболеть",
    "voolama":"течь",
    "jõuama":"прибывать, смочь",
    "tekkima":"появиться, образоваться",
    "pikutama":"лежать",
    "süütma":"разжигать",
    "viib keele alla":"язык проглотишь",
    "kaunistama":"украшать",
    "segama":"запутать",
    "praema":"жарить",
    "keetma":"варить",
    "ajama":"гнать (кого)",
    "lobisema":"болтать",
    "juttu ajama":"разговаривать",
    "kiitma":"хвалить",
    "seletama":"объяснять",
    "valmistama":"готовить",
    "üles leidma":"находить",
    "keerama":"вращать",
    "lõhkuma":"разбить, сломать",
    "suunama":"направить",
    "laekama":"поступить",
    "saabuma":"прибыть",
	"kurjuma":"ругаться",
    "närima":"грызть",
	"varastama":"воровать",
	"keelama":"запрещать",
	"tohtima":"võima",
	"kihutama":"гнать мчаться",
	"rippuma":"повиснуть, свисать, висеть",
	
}