const dictionary = {
    "mahtuma":"вмещать",
    "hädaldama":"жаловаться",
    "arutama":"обсуждать",
    "astuma":"заходить",
    "kujutama":"представлять",
    "keerama":"вращать",
    "virisema":"ныть",
    "nuusutama":"нюхать",
    "hüüdma":"кричать, звать",
    "kõndima":"гулять",
    "lehvitama":"махать",
    "krabistama":"шуршать",
    "pidama":"tähistama",
    "hoidma":"держать",
    "lööma":"взбить, бить",
    "hapuma":"киснуть",
    "õiendama":"вытягивать, выпрямлять",
    "paistma":"виднеться, торчать",
    "nautima":"наслаждаться",
    "pistma":"сунуть",
    "peitma":"спрятать",
    "sattuma":"попасть",
    "valama":"налить, насыпать",
    "lubama":"обещать, разрешать",
    "esindama":"представлять",
    "paluma":"просить",
    "soovitama":"рекомендовать",
    "saavutama":"достигать",
	"tasuma":"maksma",
	"pöörama":"keerama",
    "kukkuma":"упасть",
    "siirduma":"направляться",
    "hellitama":"баловать",
    "kahtlema":"сомневаться",
    "voolama":"течь",
    "jõuama":"прибывать, смочь",
    "tekkima":"создаваться, образоваться",
    "pikutama":"лежать",
    "süütma":"разжигать",
    "kaunistama":"украшать",
    "segama":"запутать",
    "praema":"жарить",
    "keetma":"варить",
    "ajama":"гнать (кого)",
    "lobisema":"болтать",
    "kiitma":"хвалить",
    "seletama":"объяснять",
    "valmistama":"готовить",
    "keerama":"вращать",
    "lõhkuma":"разбить, сломать",
    "suunama":"направить",
    "laekama":"поступить",
    "saabuma":"прибыть",
	"kurjuma":"ругаться",
    "närima":"грызть",
	"varastama":"воровать",
	"keelama":"запрещать",
	"tohtima":"võima",
	"kihutama":"гнать мчаться",
	"rippuma":"повиснуть, свисать, висеть",
	"olenema, sõltuma":"зависеть",
	"sisestama":"вводить, набирать",
	"taotlema":"ходатайствовать",
	"väljuma":"выходить",
	"häirima":"тревожить, беспокоить",
	"paluma":"просить",
	"eksima":"ошибиться, сбиваться",
	"kandma":"носить (одежду)",
	"kinnitama":"закреплять",
	"teritama":"точить",
	"vaevama":"мучить",
	"hingama":"дышать",
	"kaebama":"жаловаться",
	"kraadima":"мерить температуру",
	"pääsema":"освободиться, спасаться",
	"päästma":"спасать",
	"tõmbama":"тянуть",
	"tundma":"чувствовать, знать",
	"asendama":"замещать, подменять",
	"usaldama":"доверять",
	"sisenema":"войти, зайти",
	"märjaks tegema":"смочить",
	"paistetama":"распухать, отекать, вздуваться",
	"pai tegema":"поглаживать",
	"määrama":"установить, присудить, прописать",
	"karastama":"закаляться",
	"higistama":"потеть, пропотеть",
	"rahustama":"успокаивать",
	"lõõgastama":"расслаблять",
	"piinlema":"мучиться, страдать",
	"kannatama":"терпеть, испытывать",
	"aevastama":"чихать"
}