const dictionary = [
["aega kinni panna - забронировать время, записаться"],
["ära parandama - починить"],
["ära sulama - таять"],
["asju ajama - по делам"],
["ausalt öeldes - честно говоря"],
["ei lähe käima - не работает"],
["grippi jääma - заболеть"],
["haigeks jääma - заболеть"],
["hoiama vormis - держаться в форме"],
["igaks juhuks - на всякий случай"],
["juba parem - уже получше"],
["juttu ajama - разговаривать"],
["kaasas olema - быть при себе"],
["käed kinni - руки заняты"],
["katki minema - поломаться"],
["kätte saama - получать на руки, приобретать"],
["kinni jääma - застрять"],
["kinni pidama - останавливать"],
["kõigele vaatamata - несмтря на все"],
["kokku saama - собраться"],
["korda tegema - привести в порядок"],
["korda tegema - приводить в порядок, ремонтировать"],
["kui läheb paremaks - когда станет лучше"],
["läbi laskma - пропускать, течь"],
["lõbutse hästi - хорошо повеселись"],
["ma ei viitsi - мне лень"],
["maha jääma - отстать"],
["maha jätma - бросать, оставлять"],
["maha jätma - оставить"],
["maha minema - сойти выйти"],
["maha võtma - снимать, сбавлять"],
["maitse asi - дело вкуса"],
["meeldiv kasulikuga ühendada - совместить приятное с полезным"],
["mis lahti on - что случилось"],
["mis lahti on - что стряслось"],
["miski on mäda - что-то здесь нечисто"],
["mul on halb olla - мне было плохо"],
["mul on halb olla - мне плохо, мне нездоровится"],
["mulle näib - мне кажется"],
["mure südamel - грустно на сердце"],
["nii öelda - так сказать"],
["nii öelda - так сказать"],
["niipea kui võimalik - как можно скорее"],
["ole lahke - будь добр"],
["olen täis - пьяный"],
["oma silm on kuningas - лучше сто раз увидеть"],
["omadega õhtul - сломался, оставляет желать лучшего"],
["omal käel - в неофициальном порядке, частным путем"],
["päev on kinni - день занят"],
["palaviku vastu - против (от) температуры"],
["pea on täitsa segi - каша в голове"],
["pole õrna aimugi - понятия не имею"],
["pole viga - ничего (всё ок)"],
["pole viga - ничего страшного"],
["põrkama kokku - столкнуться"],
["rahul olema - быть спокойным"],
["selles mõttes - в том смысле"],
["selles mõttes - в этом смысле"],
["Sellisel juhul - в таком случае"],
["sooviksin aega arstile - хотел бы номерок к врачу"],
["sooviksin aega arstile - хочу записаться к врачу"],
["sõpradeks saama - подружиться"],
["süda paha - тошнит"],
["taat ja memm - дед и баба"],
["tema kohta - по поводу его/ее"],
["üles leidma - находить"],
["üsna halvasti - весьма плохо"],
["üsna halvasti - довольно плохо"],
["välja vahetama - поменять, сменить"],
["vastu pidama - продержаться, выстоять"],
["vastu tulema - идти навстречу, встречать"],
["viib keele alla - язык проглотишь"],
]