const dictionary = [
	["See on liik - Это уже слишком"],
	["rahvusvaheline kosmosejaam - МКС"],
	["Jala käima - Ходить пешком"],
	["läheb vaja - понадобится"],
	["ega sulle ei meeldi - тебе не нравится?/нравится ли тебе?"],
	["meil on palju ühist - у нас много общего"],
	["Läks puruks - Вдребезги"],
	["Märg nagu kass - мокрый как кошка"],
	["Puhkamist alustama - начать отпуск"],
	["Astronoomia huviline - астроном любитель"],
	["pea lõhub valutada - голова разламывается/трещит"],
	["nutikad viivad elu edasi - Смышленые двигают жизнь вперед"],
	["pole mõtet kurvastada - Нет смысла печалиться"],
	["Ma kahtlen endas - Я сомневаюсь в себе"],
	["sisustama oma kodu - обставлять свой дом"],
	["käima panema - заводить, запускать"],
	["pane peod käima - начинай вечеринку"],
	["nägu(sid) tegema - кривляться, делать вид"],
	["saladusi hoidma - хранить секреты"],
	["leiba teenima - зарабатывать на хлеб"],
	["elatist teenima - зарабатывать на жизнь"],
	["lepingu üles öelda - расторгнуть договор"],
	["kahju kannama - понести убытки"],
	["silm särab - глаз сверкает"],
	["ennast maksma panema - самоутвердиться"],
	["ette tulema - выходить, так вышло"],
	["üles kaaluma - перевешивать (что лучше)"],
	["silma peal hoidma - следить"],
	["nagu puhas mesi - как чистый мёд"],
	["juttu rääkima - говорить о том, о сём"],
	["aega kinni panna - забронировать время, записаться"],
	["ajasin segamini - перепутал"],
	["asju ajama - по делам"],
	["astu minu poolt läbi - зайди ко мне"],
	["ausalt öeldes - честно говоря"],
	["ei lähe käima - не работает"],
	["grippi jääma - заболеть"],
	["hoiama vormis - держаться в форме"],
	["igaks juhuks - на всякий случай"],
	["juba parem - уже получше"],
	["juttu ajama - разговаривать"],
	["kaasas olema - быть при себе"],
	["katki minema - поломаться"],
	["kinni jääma - застрять"],
	["kinni pidama - останавливать"],
	["kokku saama - собраться"],
	["korda tegema - приводить в порядок, ремонтировать"],
	["kui läheb paremaks - когда станет лучше"],
	["käed kinni - руки заняты"],
	["kõigele vaatamata - несмтря на все"],
	["läbi laskma - пропускать, течь"],
	["läbi otsinud - везде искал, обыскался"],
	["läksin näost punaseks - покраснел"],
	["lõbutse hästi - хорошо повеселись"],
	["ma ei viitsi - мне лень"],
	["ma ei viitsi - мне лень, не хочется"],
	["maha jätma - бросать, оставлять"],
	["maha jääma - отстать"],
	["maha minema - сойти выйти"],
	["maha võtma - снимать, сбавлять"],
	["maitse asi - дело вкуса"],
	["meeldiv kasulikuga ühendada - совместить приятное с полезным"],
	["mis lahti on - что случилось"],
	["mis sa nüüd - что ты"],
	["miski on mäda - что-то здесь нечисто"],
	["mul on halb olla - мне плохо, мне нездоровится"],
	["mulle näib - мне кажется"],
	["mure südamel - грустно на сердце"],
	["nii öelda - так сказать"],
	["niipea kui võimalik - как можно скорее"],
	["ole lahke - будь добр"],
	["olen täis - пьяный"],
	["oma silm on kuningas - лучше сто раз увидеть"],
	["omadega õhtul - сломался, оставляет желать лучшего"],
	["omal käel - в неофициальном порядке, частным путем"],
	["palaviku vastu - против (от) температуры"],
	["pea on täitsa segi - каша в голове"],
	["pole viga - ничего (всё ок)"],
	["pole õrna aimugi - понятия не имею"],
	["päev on kinni - день занят"],
	["põrkama kokku - столкнуться"],
	["rahul olema - быть спокойным"],
	["selga proovima - примерять"],
	["selles mõttes - в этом смысле"],
	["sellisel juhul - в таком случае"],
	["sooviksin aega arstile - хочу записаться к врачу"],
	["sõpradeks saama - подружиться"],
	["süda paha - тошнит"],
	["taat ja memm - дед и баба"],
	["tema kohta - по поводу его/ее"],
	["vahet pole - без разницы"],
	["vastu pidama - продержаться, выстоять"],
	["vastu tulema - идти навстречу, встречать"],
	["viib keele alla - язык проглотишь"],
	["välja vahetama - поменять, сменить"],
	["ära maksama - заплатить"],
	["ära parandama - починить"],
	["üles leidma - находить"],
	["üsna halvasti - довольно плохо"],
	["miks mitte - почему нет"],
	["olen nõus - я согласен"],
	["muidugi - конечно"],
	["kindlasti - "],
	["teil on õigus - вы правы"],
	["ma arvan ka nii - я тоже так считаю"],
	["see on tõesti hea mõte - это действительно хорошая мысль"],
	["loomulikult - естественно"],
	["mina nii ei arva - я так не думаю"],
	["ma pole päris kindel - я не совсем уверен"],
	["nii see küll ei olnud - это точно было не так"],
	["see pole tõsi - это неправда"],
	["pole võimalik - невозможно"],
	["ma kahtlen selles - "],
	["ma ei usu seda - я в это не верю"],
	["ma ei arva, et... - я не думаю, что "],
	["minu arvates - по-моему"],
	["ma arvan, et... - я считаю, что"],
	["ma mõtlen, et - я думаю, что"],
	["mida teie arvate? - как вы считаете?"],
	["kuidas teile tundub - как вам кажется"],
	["te saite minust valesti aru - вы меня неправильно поняли"],
	["ma pean täpsustama, et... - я должен уточнить, что"],
	["ma ei mõelnud seda nii - я об этом так не думал"],
	["mul on meeles, et - мне помнится, что"],
	["mul ei olnud meeles, et - "],
	["kahjuks ma ei mäleta, kas - к сожалению, я не помню, что"],
	["ma olen unustanud, mis - я забыл, что"],
	["mul tuli meelde, et - я вспомнил, что"],
	["mul ei tule meelde - я не вспомнил"],
	["mul läks meelest - я забыл / вылетело из головы"],
	["las ma mõtlen - дай я подумаю"],
	["kuidas seda öelda - как сказать"],
	["seda on raske öelda - это трудно сказать"],
	["võib-olla peaks... - возможно надо бы..."],
	["ma hästi ei usu, et... - "],
	["neid asju on raske võrrelda - эти вещи трудно сравнить"],
	["neid kahte on raske võrrelda - эти два трудно сравнить"],
	["mulle meeldib see teine rohkem - мне второй больше нравится"],
	["see on palju parem - это намного лучше"],
	["kumb sulle meeldib - который из двух тебе нравится"],
	["mulle meeldivad mõlemad - мне оба нравятся"],
	["palun, kas te saaksite mind aidata - пожалуйста, вы могли бы мне помочь"],
	["kas ma võin teid aidata - я могу вам помочь"],
	["kas teil on abi vaja - вам нужна помощь?"],
	["lubage, ma aitan - разрешите, я помогу"],
	["ma võin sind aidata - я могу тебе помочь"],
	["mis sa arvad, kui läheksime... - как считаешь, если сходим..."],
	["kas sa tahaksid... - ты хотел бы..."],
	["kas sul on täna aega - у тебя есть сегодня время?"],
	["kuidas oleks, kui... - а что если бы..."],
	["ma kardan, et - боюсь, что"],
	["kahjuks - к сожалению"],
	["mul on väga kahju, aga - мне очень жаль, но"],
	["küll on kahju, et - очень жаль, что"],
	["tulge meile külla - приходите к нам в гости"],
	["tule mind vaatama - заходи ко мне"],
	["kas sa saad minu juurde tulla - можешь ко мне прийти?"],
	["tulge meie juurest läbi - заходите к нам"],
	["sa võiksid mulle külla tulla - мы мог бы прийти ко мне в гости"],
	["esiteks... teiseks... kolmandaks... - во-первых... во-вторых..."],
	["kõigepealt - прежде всего"],
	["esmalt - "],
	["esiteks... siis - "],
	["üldiselt... - вообше"],
	["lühidalt... - короче"],
	["kokkuvõtteks... - в итоге"],
	["häid pühi - хорошего праздника"],
	["ilusat suve - красивого лета"],
	["mõnusat puhkust - приятного отпуска"],
	["kivi kotti - ни пуха"],
	["head põrumist - "],
	["head reisi - хорошей поездки"],
	["head isu / jätku leivba - приятного аппетита (2)"],
	["jõudud tööle - бог помощь"],
	["kena päeva jätku - хорошего остатка дня"],
	["kõike head - всего хорошего"],
]