const dictionary = {
	"aega kinni panna":"",
	"asju ajama":"по делам",
    "pea on täitsa segi":"каша в голове",
    "taat ja memm":"дед и баба",
    "igaks juhuks":"на всякий случай",
    "maitse asi":"дело вкуса",
    "pole õrna aimugi":"понятия не имею",
    "Sellisel juhul":"в таком случае",
    "niipea kui võimalik":"как можно скорее",
    "lõbutse hästi":"хорошо повеселись",
	"olen täis":"пьяный",
    "süda paha":"тошнит",
    "oma silm on kuningas":"лучше сто раз увидеть",
    "päev on kinni":"день занят",
    "käed kinni":"руки заняты",
    "ära sulama":"таять",
    "kinni pidama":"останавливать",
    "mulle näib":"мне кажется",
	"maha jääma":"отстать",
	"maha minema":"сойти выйти",
    "grippi jääma":"заболеть",
    "viib keele alla":"язык проглотишь",
    "juttu ajama":"разговаривать",
	"kokku saama":"собраться",
    "üles leidma":"находить",
	"maha võtma":"снимать, сбавлять",
	"ole lahke":"будь добр",
	"põrkama kokku":"столкнуться",
	"mis lahti on":"что случилось",
	"miski on mäda":"что-то здесь нечисто",
	"läbi laskma":"пропускать, течь",
	"kinni jääma":"застрять",
	"korda tegema":"приводить в порядок, ремонтировать",
	"omadega õhtul":"сломался, оставляет желать лучшего",
	"pole viga":"ничего страшного",
	"üsna halvasti":"довольно плохо",
	"mul on halb olla":"мне было плохо",
	"sooviksin aega arstile":"хотел бы номерок к врачу",
	"nii öelda":"так сказать",
	"selles mõttes":"в том смысле",
	"maha jätma":"оставить",
}